### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by bance** [aquaticus/esp32_composite_video_lib#7]
Hello, followed the instruction to build the minimal test screen app, but encountered the following error:

c:\pio\crt_aquaticus\components\lvgl\src/widgets/meter/lv_meter.h:22:2: error: #error "lv_meter: Complex drawing is required. Enable it in lv_conf.h (LV_USE_DRAW_MASKS 1)"

however, this particular configuration option (use draw masks) is not available in the lvgl component configuration section in menuconfig. the "complex drawing" is enabled by default. any clue on this?

thanks

**Comment by aquaticus** [comment]
It seems the current `master` branch on LVGL repo got compilation problems.
Use stable version of LVGL. For example:
```
cd components/lvgl
git checkout release/v8.2
cd ../..
idf.py clean
idf.py build
```
