### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by danjulio** [aquaticus/esp32_composite_video_lib#9]
Hey, not an issue, but since I didn't find an email link for you I thought I'd give you a shout out here.  Very nice work.  Thanks for publishing this.  It let me quickly throw together an analog video output thermal imaging camera ([https://github.com/danjulio/tCamMiniAnalog](https://github.com/danjulio/tCamMiniAnalog)).

**Comment by aquaticus** [comment]
Hi @danjulio 

good to hear the library is used in real life. And in such cool project!

**Comment by danjulio** [comment]
And thank you!
